openapi: 3.0.1
info:
  title: IAsistant
  description: Aplicación web que permite a los usuarios crear y personalizar asistentes de inteligencia artificial.
  version: 1.0.0
servers:
  - url: http://localhost:5100/api/
tags:
  - name: IAssistants
    description: Endpoints relacionados con usuarios y asistentes.

paths:
  /users/{email}/{password}:
    get:
      tags:
        - users
      summary: Obtiene un usuario por email y contraseña
      parameters:
        - name: email
          in: path
          required: true
          description: Correo electrónico del usuario
          schema:
            type: string
        - name: password
          in: path
          required: true
          description: Contraseña del usuario
          schema:
            type: string
      responses:
        '200':
          description: Usuario autenticado con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  status:
                    type: string
                  message:
                    type: string
                  id_user:
                    type: string
        '400':
          description: Error de autenticación
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /users:
    post:
      tags:
        - users
      summary: Crea un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                form:
                  type: object
                  properties:
                    name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
                    age:
                      type: integer
                    password:
                      type: string
                  required:
                    - name
                    - email
                    - password
      responses:
        '200':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '400':
          description: Error al crear usuario
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '409':
          description: El correo ya se encuentra en uso
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /assistants/{id_user}:
    get:
      tags:
        - assistants
      summary: Obtiene los asistentes de un usuario
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
            description: ID del usuario
      responses:
        '200':
          description: Asistentes obtenidos exitosamente
        '500':
          description: Error al obtener los asistentes

  /assistants:
    post:
      tags:
        - assistants
      summary: Crea un nuevo asistente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    name:
                      type: string
                    id_user:
                      type: string
                    speciality:
                      type: string
      responses:
        '200':
          description: Asistente creado exitosamente
        '500':
          description: Error al crear el asistente

  /assistants/chat:
    post:
      tags:
        - assistants
      summary: Enviar una pregunta al asistente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
                initial:
                  type: string
                conversationHistory:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: Respuesta del asistente obtenida exitosamente
        '400':
          description: Error en la solicitud
        '500':
          description: Error interno del servidor

  /assistants/update:
    put:
      tags:
        - assistants
      summary: Actualiza un asistente existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    _id:
                      type: string
                    name:
                      type: string
      responses:
        '200':
          description: Asistente actualizado exitosamente
        '500':
          description: Error al actualizar el asistente

  /assistants/delete/{_id}:
    delete:
      tags:
        - assistants
      summary: Elimina un asistente
      parameters:
        - name: _id
          in: path
          required: true
          schema:
            type: string
            description: ID del asistente a eliminar
      responses:
        '200':
          description: Asistente eliminado exitosamente
        '500':
          description: Error al eliminar el asistente
